### ISSUE TITLE
[Bug] Leaderboard

### ISSUE THREAD

**Issue by Pokefree** [TSEcho/PokeTeams_Plugin#3]
When i use the commands /teams leaderboard i don't see all the team. Do you think you can make all the team and sorted them by their win ratio ? Thanks for your work, it's amazing.
![image](https://user-images.githubusercontent.com/46332725/51066176-01123d00-1609-11e9-8abd-44fd9bb390d1.png)

**Comment by Pokefree** [comment]
Ok thanks for the information !

**Comment by TSEcho** [comment]
I should note that I changed this feature now so teams without any data will appear as 0%. Granted there are only 10 entries per page so you will often not see the 0%s but it will still be there
